# DROP DATABASE Pexeso;

CREATE DATABASE Pexeso
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_czech_ci;

USE Pexeso;

CREATE TABLE HerniPlochy (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Stav VARCHAR(250),
  CasPoslednihoTahu TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE Karty (
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  HerniPlochaID INT NOT NULL,
  CisloKarty INT DEFAULT 0 NOT NULL,
  Stav VARCHAR(250) ,
  PoradiKarty INT NOT NULL DEFAULT 0,
  CONSTRAINT HerniPlocha_FK FOREIGN KEY (HerniPlochaID) REFERENCES HerniPlochy (ID)
);
